#include "BuildPipeline.h"
#include <map>
#include <vector>
#include <unordered_set>

namespace MHT {
	namespace {
        /**
         * 生成序列化函数
         */
        std::string GenerateSerializeFunctionFormatted(
            const std::map<std::string, std::vector<MemberVariable>>& classParamsMap,
            const std::string& templateArg = "Archive"
        ) {
            std::ostringstream code;

            code << "template<class " << templateArg << ">\n";
            code << "void serialize(" << templateArg << "& archive) {\n";
            code << "    using ThisType = std::decay_t<decltype(*this)>;\n";
            code << "    \n";

            bool firstClass = true;
            for (const auto& [className, params] : classParamsMap) {
                if (!firstClass) {
                    code << "    } else ";
                }
                code << "if constexpr (std::is_same_v<ThisType, " << className << ">) {\n";
                code << "        archive(";
                for (size_t i = 0; i < params.size(); ++i) {
                    const MemberVariable& Variable = params[i];
                    code << Variable.name;
                    if (i < params.size() - 1) {
                        code << ", ";
                    }
                }
                code << ");\n";
                firstClass = false;
            }

            if (!classParamsMap.empty()) {
                code << "    }\n";
            }
            code << "}\n";
            return code.str();
        }

        std::string ConvertFunctionToMacro(const std::vector<std::string>& funcStrings, const std::string& macroName = "GENERATE_BODY") {
            std::ostringstream result;
            result << "#define " << macroName << "() \\\n";

            bool firstLine = true;

            for (const auto& funcString : funcStrings) {
                std::stringstream ss(funcString);
                std::string line;

                while (std::getline(ss, line)) {
                    // 去除换行符和首尾空白
                    line.erase(std::remove(line.begin(), line.end(), '\r'), line.end());

                    size_t start = line.find_first_not_of(" \t");
                    if (start == std::string::npos) continue;

                    line = line.substr(start);

                    if (!firstLine) {
                        result << " \\\n";
                    }

                    result << "    " << line;
                    firstLine = false;
                }
            }

            return result.str();
        }

        std::string GenerateFileWithCode(
            const std::vector<std::string>& codeLines,
            const std::string& generatorName = "MagicHeaderTool",
            const std::string& additionalInfo = ""
        ) {
            std::ostringstream result;

            // 生成文件头部
            result << "#pragma once\n\n";
            result << "// ============================================================================\n";
            result << "// This file is generated by " << generatorName << ".\n";
            result << "// DO NOT MODIFY THIS FILE MANUALLY!\n";
            result << "// Any manual changes will be overwritten.\n";

            if (!additionalInfo.empty()) {
                result << "// \n";
                result << "// " << additionalInfo << "\n";
            }

            result << "// ============================================================================\n\n";

            // 追加用户代码
            for (const auto& line : codeLines) {
                result << line << "\n";
            }

            return result.str();
        }
	}

	namespace Pipeline {
        struct MetaData {
            std::string headerName;
            std::string MetadataSrc;
            std::string Metadata;

            void SetMetadataSrc(const std::string& MetadataSrc, const std::string& headerName)
            {
                this->MetadataSrc = MetadataSrc;
                this->headerName  = headerName;
            }
            void SetMetadata(const std::string& Metadata) { this->Metadata = Metadata; }
        };

		bool GenerateObjectMetadata() {
            const auto& MagicEngineClasss = MagicBuildData::Get().GetRefMagicEngineClasss();
            auto& MagicObjectMetadatas = MagicBuildData::Get().GetRefMagicObjectMetadatas();
            std::unordered_set<std::string> AllArea;
            std::vector<MetaData> MetaDatas;

            // 获取所有不重复的区域
            for (size_t i = 0; i < MagicEngineClasss.size(); i++)
            {
                auto& MagicEngineClass = MagicEngineClasss[i];
                AllArea.insert(MagicEngineClass.headerName);
            }

            // 为每个文件生成对应的生成信息 之后生成元数据
            for (const auto& Area : AllArea) 
            {
                std::map<std::string, std::vector<MemberVariable>> GenerateInformationMap;
                for (size_t y = 0; y < MagicEngineClasss.size(); y++)
                {
                    auto& MagicEngineClass = MagicEngineClasss[y];
                    if (Area == MagicEngineClass.headerName) {
                        GenerateInformationMap[MagicEngineClass.className] = MagicEngineClass.members;
                    }
                }
                // 生成元数据
                std::string src = GenerateSerializeFunctionFormatted(GenerateInformationMap);
                MetaDatas.emplace_back().SetMetadataSrc(src, Area);
            }

            // 之后将我们生成的元数据使用宏包裹
            for (size_t i = 0; i < MetaDatas.size(); i++)
            {
                auto& MetaData = MetaDatas[i];
                std::string MetaDataScript = ConvertFunctionToMacro({ MetaData.MetadataSrc });
                MetaData.SetMetadata(MetaDataScript);
            }

            // 之后生成文件头与解释说明
            for (size_t i = 0; i < MetaDatas.size(); i++)
            {
                auto& MetaData = MetaDatas[i];
                std::string MetaDataScript = GenerateFileWithCode({ MetaData.Metadata });
                MetaData.SetMetadata(MetaDataScript);
            }

            // 最后把数据给MagicBuildData
            for (size_t i = 0; i < MetaDatas.size(); i++)
            {
                auto& MetaData = MetaDatas[i];

                std::string ModelName = "NOT";
                for (size_t y = 0; y < MagicEngineClasss.size(); y++)
                {
                   const auto& MagicEngineClass = MagicEngineClasss[y];
                    if (MagicEngineClass.headerName == MetaData.headerName) {
                        ModelName = MagicEngineClass.moudelName;
                    }
                }

                MagicObjectMetadatas.push_back({ MetaData.headerName , MetaData.Metadata,ModelName });
            }

			return true;
		}
	}
}