#include "BuildPipeline.h"
#include <map>
#include <vector>
#include <unordered_set>

namespace MHT {
	namespace {
        struct LocalSourcesIndex {
            enum class Sort : uint8_t {
                BeforeBody,
                InBody,
                AfterBody
            };

            std::string Source;
            Sort index = Sort::InBody;
        };

        struct LocalValidateParameter {
            std::string Parameter;
            bool consistent = false;
        };

        std::string GenerateEmptyMacros(const std::vector<std::string>& classNames) {
            std::ostringstream code;

            for (const auto& className : classNames) {
                // Generate GENERATE_SERIALIZE_XXX() NOT
                code << "#define GENERATE_SERIALIZE_" << className << "() \\\n";
                code << "\n";

                // Generate GENERATE_REFLECTION_XXX() NOT
                code << "#define GENERATE_REFLECTION_" << className << "() \\\n";
                code << "\n";
            }

            return code.str();
        }

        /**
         * 生成序列化函数
         */
        std::string GenerateClassBodyFunction() {
            std::ostringstream code;
            code << "    virtual uint64_t GetClassId() const {\n";
            code << "        \n";
            code << "        return GET_CLASS_ID_##CLASS_NAME;\n";
            code << "    }\n";

            // use macros generate class function
            code << "    GENERATE_SERIALIZE_##CLASS_NAME()\n";
            code << "    GENERATE_REFLECTION_##CLASS_NAME()\n";

            // Set constructor parameters
            code << "    ##CLASS_NAME() : Core::Object() {                          \n";
            code << "       this->type = ObjectType::##OBJECT_TYPE;                 \n";
            code << "       this->class_has = GENERATE_OBJECT_TAG_##CLASS_NAME;     \n";
            code << "    }                                                          \n";
            code << "                                                               \n";
            code << "    ~##CLASS_NAME() {                                          \n";
            code << "    }                                                          \n";
            return code.str();
        }

        /**
         * 生成 GetClassId 函数
         * @param classIdMap 类名和类ID的映射表
         * @return 宏
        */
        std::string GenerateClassIdSpecificMacros(
            const std::map<std::string, size_t>& classIdMap
        ) {
            std::ostringstream code;

            for (const auto& [className, classId] : classIdMap) {
                // 生成 GET_CLASS_ID_XXX 宏
                code << "#define GET_CLASS_ID_" << className << " " << classId << "ULL\n";
            }

            return code.str();
        }

        std::string GenerateObjectTagSpecificMacros(
            const std::map<std::string, size_t>& ObjectTagMap
        ) {
            std::ostringstream code;

            for (const auto& [className, Tag] : ObjectTagMap) {
                // 生成 GENERATE_OBJECT_TAG_XXX 宏
                code << "#define GENERATE_OBJECT_TAG_" << className << " " << Tag << "\n";
            }

            return code.str();
        }

        std::string GenerateClassSerializationMacros(
            const std::map<std::string, std::vector<MemberVariable>>& classParamsMap
        ) {
            std::ostringstream code;

            for (const auto& [className, params] : classParamsMap) {
                // 生成 GENERATE_SERIALIZE_XXX 宏
                code << "#ifdef GENERATE_SERIALIZE_" << className << "\n";
                code << "#undef GENERATE_SERIALIZE_" << className << "\n";
                code << "#endif\n\n";

                code << "#define GENERATE_SERIALIZE_" << className << "() \\\n";

                code << "    template<class Archive>                        \\\n";
                code << "    void serialize(Archive& archive) {             \\\n";
                code << "        archive(";
                for (size_t i = 0; i < params.size(); ++i) {
                    code << params[i].name;
                    if (i < params.size() - 1) {
                        code << ", ";
                    }
                }
                code << ");                                                 \\\n";
                code << "    }                                              \\\n";
                code << "\n";
            }

            return code.str();
        }

        std::string GenerateFileWithCode(
            const std::vector<std::string>& codeLines,
            const std::string& generatorName = "MagicHeaderTool",
            const std::string& additionalInfo = ""
        ) {
            std::ostringstream result;

            // 生成文件头部
            result << "#pragma once\n\n";
            result << "// ============================================================================\n";
            result << "// This file is generated by " << generatorName << ".\n";
            result << "// DO NOT MODIFY THIS FILE MANUALLY!\n";
            result << "// Any manual changes will be overwritten.\n";

            if (!additionalInfo.empty()) {
                result << "// \n";
                result << "// " << additionalInfo << "\n";
            }

            result << "// ============================================================================\n\n";

            // 此时我们不需要Object上的默认宏了
            result << "#ifdef GENERATE_BODY\n";
            result << "#undef GENERATE_BODY\n";
            result << "#endif\n\n";

            // 追加用户代码
            for (const auto& line : codeLines) {
                result << line << "\n";
            }

            return result.str();
        }

        std::string ConvertFunctionToMacro(const std::vector<LocalSourcesIndex>& funcStrings, const std::string& macroName = "GENERATE_BODY", const std::string& macroSignature = "...") {
            std::ostringstream result;
            result << "#define " << macroName << "(" << macroSignature << ") \\\n";
            result << "public: " << " \\\n";                // 这里我们默认使用公开区域设置

            bool firstLine = true;

            for (const auto& funcString : funcStrings) {
                if (funcString.index != LocalSourcesIndex::Sort::InBody)
                    continue;   // is no InBody continue

                std::stringstream ss(funcString.Source);
                std::string line;

                while (std::getline(ss, line)) {
                    // 去除换行符和首尾空白
                    line.erase(std::remove(line.begin(), line.end(), '\r'), line.end());

                    size_t start = line.find_first_not_of(" \t");
                    if (start == std::string::npos) continue;

                    line = line.substr(start);

                    if (!firstLine) {
                        result << " \\\n";
                    }

                    result << "    " << line;
                    firstLine = false;
                }
            }

            return result.str();
        }

        bool ValidateParameters(
            const std::vector<LocalValidateParameter>& a,
            const std::vector<std::string>& b
        ) {
            // 检查长度是否一致
            if (a.size() != b.size()) {
                if (a.size() > b.size()) {
                    TOOL::Log::Error("Parameter count mismatch: expected " +
                        std::to_string(b.size()) + " parameters, but got " +
                        std::to_string(a.size()) + " parameters (too many)");
                }
                else {
                    TOOL::Log::Error("Parameter count mismatch: expected " +
                        std::to_string(b.size()) + " parameters, but got " +
                        std::to_string(a.size()) + " parameters (too few)");
                }
                return false;
            }

            // 检查每个参数是否一致
            for (size_t i = 0; i < a.size(); ++i) {
                LocalValidateParameter Parameter = a[i];
                if (Parameter.consistent) {
                    if (Parameter.Parameter != b[i]) {
                        TOOL::Log::Error("Parameter mismatch at index " + std::to_string(i) +
                            ": expected \"" + b[i] + "\", but got \"" + Parameter.Parameter + "\"");
                        return false;
                    }
                }
                else {
                    // 没有绝对比配那么只要有这个参数就可以
                }
            }

            return true;
        }

        std::string MergeCode(const std::string& code1, const std::string& code2) {
            std::ostringstream result;
            result << code1 << "\n" << code2;
            return result.str();
        }

        uint64_t GlobalAutoincrementedValue() {
            static uint64_t value = 0; // 初始化为0
            return value++;
        }
	}

	namespace Pipeline {
        struct LocalMetadataSource {
            std::string Source;
            bool NeedMacro = true;
        };

        struct LocalMetaData {
            std::string headerName;
            std::vector<LocalMetadataSource> Sources;
            std::string Metadata;

            void SetSources(const std::vector<LocalMetadataSource>& Sources, const std::string& headerName)
            {
                this->Sources = Sources;
                this->headerName  = headerName;
            }
            void SetMetadata(const std::string& Metadata) { this->Metadata = Metadata; }
        };

        struct LoaclGenerateOptionalInformationMap {
            std::map<std::string, std::vector<MemberVariable>> GenerateInformationMap_Serialize;
            std::map<std::string, std::vector<MemberVariable>> GenerateInformationMap_Reflection;
        };

		bool GenerateObjectMetadata() {
            const auto& MagicEngineClasss =     MagicBuildData::Get().GetRefMagicEngineClasss();
            auto& MagicObjectMetadatas =        MagicBuildData::Get().GetRefMagicObjectMetadatas();
            std::unordered_set<std::string> AllArea;
            std::vector<LocalMetaData> MetaDatas;

            // 获取所有不重复的区域
            for (size_t i = 0; i < MagicEngineClasss.size(); i++)
            {
                auto& MagicEngineClass = MagicEngineClasss[i];
                AllArea.insert(MagicEngineClass.headerName);
            }

            // 为每个文件生成对应的生成信息 之后生成元数据
            for (const auto& Area : AllArea) 
            {
                std::vector<std::string> CurrentAreaAllClass;
                LoaclGenerateOptionalInformationMap OptionalMap;
                std::map<std::string, size_t> GenerateInformationMap_GetClassId;
                std::map<std::string, size_t> GenerateInformationMap_ObjectTag;
                // 校验参数是否正确
                for (size_t y = 0; y < MagicEngineClasss.size(); y++) {
                    auto& MagicEngineClass = MagicEngineClasss[y];
                    if (Area == MagicEngineClass.headerName) {
                        std::vector<LocalValidateParameter> TargetParameter = {
                            {MagicEngineClass.className,true},      // 第一个参数是输入class的Name
                            {"ObjectType",false},                   // 第二个参数是输入Object的属于谁
                            {"ObjectTag",false},                   // 第三个参数是输入Object的标志
                            // more ...
                        };
                        if (!ValidateParameters(TargetParameter, MagicEngineClass.GenerateBody)) // 参数校验
                            return false;

                        // 记录当前文件的所有使用MHT的Class
                        CurrentAreaAllClass.push_back(MagicEngineClass.className);

                        // 填充Map
                        for (size_t i = 0; i < MagicEngineClass.ClassType.size(); i++)
                        {
                            auto& ClassType = MagicEngineClass.ClassType[i];
                            if (ClassType == "MSERIALIZATION") {
                                OptionalMap.GenerateInformationMap_Serialize[MagicEngineClass.className] = MagicEngineClass.members;
                            }
                            else if (ClassType == "MREFLECTION") {
                                OptionalMap.GenerateInformationMap_Reflection[MagicEngineClass.className] = MagicEngineClass.members;
                            }
                        }
                        GenerateInformationMap_GetClassId[MagicEngineClass.className] = GlobalAutoincrementedValue();
                        GenerateInformationMap_ObjectTag[MagicEngineClass.className] = std::hash<std::string>{}(MagicEngineClass.GenerateBody[2]); // 使用第三个参数
                    }
                }

                // 生成元数据
                std::vector<LocalMetadataSource> Sources;
                std::string src_EmptyMacros               = GenerateEmptyMacros(CurrentAreaAllClass);
                std::string src_ClassBodyFunction         = GenerateClassBodyFunction();
                std::string src_ClassGetClassIdMacros     = GenerateClassIdSpecificMacros(GenerateInformationMap_GetClassId);
                std::string src_ObjectTagMacros           = GenerateObjectTagSpecificMacros(GenerateInformationMap_ObjectTag);
                // Optional
                std::string src_ClassSerializeMacros      = GenerateClassSerializationMacros(OptionalMap.GenerateInformationMap_Serialize);

                // 构造原始元数据
                Sources.push_back({ src_EmptyMacros ,               false });
                Sources.push_back({ src_ClassBodyFunction ,         true  });
                Sources.push_back({ src_ClassGetClassIdMacros ,     false });
                Sources.push_back({ src_ObjectTagMacros ,           false });
                Sources.push_back({ src_ClassSerializeMacros ,      false });
                MetaDatas.emplace_back().SetSources(Sources, Area);
            }

            // 之后将我们生成的元数据使用宏包裹
            for (size_t i = 0; i < MetaDatas.size(); i++)
            {
                auto& MetaData = MetaDatas[i];
                std::vector<LocalSourcesIndex> Sources;
                bool AfterBody = false; // 在第一个ClassBodyMacro出现之后的Source我们认为他就是在ClassBodyMacro之后
                for (size_t y = 0; y < MetaData.Sources.size(); y++)
                {
                    auto& Source = MetaData.Sources[y];
                    if (Source.NeedMacro) AfterBody = true;
                    Sources.push_back({ Source.Source, Source.NeedMacro ? LocalSourcesIndex::Sort::InBody :
                                        AfterBody ? LocalSourcesIndex::Sort::AfterBody : LocalSourcesIndex::Sort::BeforeBody });
                }

                auto AssembleMetadata = [&Sources](std::string& target, LocalSourcesIndex::Sort index) {
                    for (size_t i = 0; i < Sources.size(); i++)
                    {
                        auto& SourceTemp = Sources[i];

                        if (SourceTemp.index == index) {
                            target = MergeCode(target, SourceTemp.Source);
                        }
                    }
                };

                std::string Source_GENERATE_BODY = ConvertFunctionToMacro(Sources, "GENERATE_BODY", "CLASS_NAME,OBJECT_TYPE,OBJECT_TAG");
                std::string Source;

                AssembleMetadata(Source, LocalSourcesIndex::Sort::BeforeBody);
                Source = MergeCode(Source, Source_GENERATE_BODY);
                AssembleMetadata(Source, LocalSourcesIndex::Sort::AfterBody);
                
                MetaData.SetMetadata(Source);
            }

            // 之后生成文件头与解释说明
            for (size_t i = 0; i < MetaDatas.size(); i++)
            {
                auto& MetaData = MetaDatas[i];
                std::string MetaDataScript = GenerateFileWithCode({ MetaData.Metadata });
                MetaData.SetMetadata(MetaDataScript);
            }

            // 最后把数据给MagicBuildData
            for (size_t i = 0; i < MetaDatas.size(); i++)
            {
                auto& MetaData = MetaDatas[i];

                std::string ModelName = "NOT";
                for (size_t y = 0; y < MagicEngineClasss.size(); y++)
                {
                   const auto& MagicEngineClass = MagicEngineClasss[y];
                    if (MagicEngineClass.headerName == MetaData.headerName) {
                        ModelName = MagicEngineClass.moudelName;
                    }
                }

                MagicObjectMetadatas.push_back({ MetaData.headerName , MetaData.Metadata,ModelName });
            }

			return true;
		}
	}
}