ImGuiCol = {
    Text                          = 0,   -- 文本
    TextDisabled                  = 1,   -- 禁用文本
    WindowBg                      = 2,   -- 窗口背景
    ChildBg                       = 3,   -- 子窗口背景
    PopupBg                       = 4,   -- 弹窗背景
    Border                        = 5,   -- 边框
    BorderShadow                  = 6,   -- 边框阴影
    FrameBg                       = 7,   -- 输入框背景
    FrameBgHovered                = 8,   -- 输入框悬停
    FrameBgActive                 = 9,   -- 输入框激活
    TitleBg                       = 10,  -- 标题栏
    TitleBgActive                 = 11,  -- 标题栏激活
    TitleBgCollapsed              = 12,  -- 标题栏折叠
    MenuBarBg                     = 13,  -- 菜单栏背景
    ScrollbarBg                   = 14,  -- 滚动条背景
    ScrollbarGrab                 = 15,  -- 滚动条滑块
    ScrollbarGrabHovered          = 16,  -- 滚动条滑块悬停
    ScrollbarGrabActive           = 17,  -- 滚动条滑块拖拽
    CheckMark                     = 18,  -- 复选框勾选
    SliderGrab                    = 19,  -- 滑块
    SliderGrabActive              = 20,  -- 滑块拖拽
    Button                        = 21,  -- 按钮
    ButtonHovered                 = 22,  -- 按钮悬停
    ButtonActive                  = 23,  -- 按钮按下
    Header                        = 24,  -- 折叠头/树节点
    HeaderHovered                 = 25,  -- 折叠头悬停
    HeaderActive                  = 26,  -- 折叠头激活
    Separator                     = 27,  -- 分隔线
    SeparatorHovered              = 28,  -- 分隔线悬停
    SeparatorActive               = 29,  -- 分隔线激活
    ResizeGrip                    = 30,  -- 拖拽调整手柄
    ResizeGripHovered             = 31,  -- 拖拽手柄悬停
    ResizeGripActive              = 32,  -- 拖拽手柄激活
    InputTextCursor               = 33,  -- 输入框光标
    TabHovered                    = 34,  -- 标签页悬停
    Tab                           = 35,  -- 标签页
    TabSelected                   = 36,  -- 标签页选中
    TabSelectedOverline           = 37,  -- 标签页选中顶线
    TabDimmed                     = 38,  -- 标签页未激活
    TabDimmedSelected             = 39,  -- 标签页未激活选中
    TabDimmedSelectedOverline     = 40,  -- 标签页未激活选中顶线
    DockingPreview                = 41,  -- 停靠预览
    DockingEmptyBg                = 42,  -- 停靠空区背景
    PlotLines                     = 43,  -- 折线图
    PlotLinesHovered              = 44,  -- 折线图悬停
    PlotHistogram                 = 45,  -- 直方图
    PlotHistogramHovered          = 46,  -- 直方图悬停
    TableHeaderBg                 = 47,  -- 表头背景
    TableBorderStrong             = 48,  -- 表格外边框
    TableBorderLight              = 49,  -- 表格内边框
    TableRowBg                    = 50,  -- 表格行背景(偶数)
    TableRowBgAlt                 = 51,  -- 表格行背景(奇数)
    TextLink                      = 52,  -- 超链接
    TextSelectedBg                = 53,  -- 文本选中背景
    TreeLines                     = 54,  -- 树节点连线
    DragDropTarget                = 55,  -- 拖放目标边框
    DragDropTargetBg              = 56,  -- 拖放目标背景
    UnsavedMarker                 = 57,  -- 未保存标记点
    NavCursor                     = 58,  -- 导航光标
    NavWindowingHighlight         = 59,  -- Ctrl+Tab窗口高亮
    NavWindowingDimBg             = 60,  -- Ctrl+Tab背景遮罩
    ModalWindowDimBg              = 61,  -- 模态窗口背景遮罩
    COUNT                         = 62,
}

ImGuiChildFlags = {
    None                   = 0,     -- 无
    Borders                = 1,     -- 显示边框
    AlwaysUseWindowPadding = 2,     -- 始终使用窗口内边距
    ResizeX                = 4,     -- 允许水平拖拽调整宽度
    ResizeY                = 8,     -- 允许垂直拖拽调整高度
    AutoResizeX            = 16,    -- 宽度自适应内容
    AutoResizeY            = 32,    -- 高度自适应内容
    AlwaysAutoResize       = 64,    -- 始终自适应(不推荐)
    FrameStyle             = 128,   -- 使用FrameBg样式代替ChildBg
    NavFlattened           = 256,   -- 导航扁平化(共享焦点)
}

ImGuiWindowFlags = {
    None                      = 0,       -- 无
    NoTitleBar                = 1,       -- 隐藏标题栏
    NoResize                  = 2,       -- 禁止调整大小
    NoMove                    = 4,       -- 禁止移动
    NoScrollbar               = 8,       -- 隐藏滚动条
    NoScrollWithMouse         = 16,      -- 禁止鼠标滚轮
    NoCollapse                = 32,      -- 禁止折叠
    AlwaysAutoResize          = 64,      -- 始终自适应大小
    NoBackground              = 128,     -- 不绘制背景
    NoSavedSettings           = 256,     -- 不保存设置到ini
    NoMouseInputs             = 512,     -- 不响应鼠标
    MenuBar                   = 1024,    -- 有菜单栏
    HorizontalScrollbar       = 2048,    -- 允许水平滚动条
    NoFocusOnAppearing        = 4096,    -- 出现时不获取焦点
    NoBringToFrontOnFocus     = 8192,    -- 获取焦点时不置顶
    AlwaysVerticalScrollbar   = 16384,   -- 始终显示垂直滚动条
    AlwaysHorizontalScrollbar = 32768,   -- 始终显示水平滚动条
    NoNavInputs               = 65536,   -- 禁止键盘导航
    NoNavFocus                = 131072,  -- 禁止导航聚焦
    UnsavedDocument           = 262144,  -- 未保存标记(标题栏圆点)
    NoDocking                 = 524288,  -- 禁止停靠
    NoNav                     = 196608,  -- = NoNavInputs | NoNavFocus
    NoDecoration              = 43,      -- = 无标题栏+无调整+无滚动+无折叠
    NoInputs                  = 197120,  -- = NoMouseInputs | NoNavInputs | NoNavFocus
}